name: IBM WebSphere Traditional®
version: 0.3.1
description: tWAS & OpenJ9 using Maven
license: Apache-2.0
language: java
maintainers:
  - name: Glenn Marcy
    email: gmarcy@us.ibm.com
    github-id: gmarcy
default-template: default
requirements:
    appsody-version: ">= 0.5.0"
    docker-version: ">= 17.09.0"
templating-data:
    twasversion: '9.0.5.3'
    baseimage: adoptopenjdk/openjdk8-openj9:jdk8u242-b08_openj9-0.18.1-ubi
    finalimage: ibmcom/websphere-traditional:9.0.5.3-ubi
    parentpomgroup: dev.appsody
    parentpomid: java-websphere-traditional
    parentpomrange: '[0.3, 0.4)'
    parentpomfilename: appsody-twas-pom.xml
